# server {
#     listen 80;
#     server_name localhost;
#     return 301 https://dev.localhost$request_uri;
# }

server {
    listen 443 ssl;
    server_name dev.localhost;

    ssl_certificate /etc/nginx/certs/dev.localhost.pem;
    ssl_certificate_key /etc/nginx/certs/dev.localhost-key.pem;

    location / {
        proxy_pass http://apache:80/dev/;
        proxy_redirect off;
    }
}
