server {
    listen 443 ssl;
    server_name ~^(?<project>.+)\.dev\.localhost$;

    ssl_certificate /etc/nginx/certs/dev.localhost.pem;
    ssl_certificate_key /etc/nginx/certs/dev.localhost-key.pem;

    location / {
        rewrite ^/(.*)$ /webstack/$project/$1 break;
        proxy_pass http://apache:80;
        proxy_redirect off;
    }
}

server {
    listen 443 ssl;
    server_name ~^(?<site>.+)\.wp\.localhost$;

    ssl_certificate /etc/nginx/certs/dev.localhost.pem;
    ssl_certificate_key /etc/nginx/certs/dev.localhost-key.pem;

    location / {
        rewrite ^/(.*)$ /sites/$site/$1 break;
        proxy_pass http://apache:80;
        proxy_redirect off;
    }
}
